/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StclUser {
        "email": string;
        "first": string;
        "imageUrl": string;
        "last": string;
    }
    interface StclUserList {
        "count": number;
    }
}
declare global {
    interface HTMLStclUserElement extends Components.StclUser, HTMLStencilElement {
    }
    var HTMLStclUserElement: {
        prototype: HTMLStclUserElement;
        new (): HTMLStclUserElement;
    };
    interface HTMLStclUserListElement extends Components.StclUserList, HTMLStencilElement {
    }
    var HTMLStclUserListElement: {
        prototype: HTMLStclUserListElement;
        new (): HTMLStclUserListElement;
    };
    interface HTMLElementTagNameMap {
        "stcl-user": HTMLStclUserElement;
        "stcl-user-list": HTMLStclUserListElement;
    }
}
declare namespace LocalJSX {
    interface StclUser {
        "email"?: string;
        "first"?: string;
        "imageUrl"?: string;
        "last"?: string;
    }
    interface StclUserList {
        "count"?: number;
    }
    interface IntrinsicElements {
        "stcl-user": StclUser;
        "stcl-user-list": StclUserList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stcl-user": LocalJSX.StclUser & JSXBase.HTMLAttributes<HTMLStclUserElement>;
            "stcl-user-list": LocalJSX.StclUserList & JSXBase.HTMLAttributes<HTMLStclUserListElement>;
        }
    }
}
